rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
mysql:
  image: mysql:latest
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=walmart
  ports:
    - "3306:3306"
redis_shipping:
  image: redis
  ports:
    - "1985:6379"
redis_orders:
  image: redis
  ports:
    - "6379:6379"
